TEST_DATA_DIR = "tests/data"
TEST_OUTPUT_DIR = f"{TEST_DATA_DIR}/outputs"

BATCH_1 = "faxes-1"
BATCH_1_DIR = f"{TEST_DATA_DIR}/{BATCH_1}"
BATCH_1_OUTPUT_DIR = f"{TEST_OUTPUT_DIR}/{BATCH_1}"

BATCH_2 = "faxes-2"
BATCH_2_DIR = f"{TEST_DATA_DIR}/{BATCH_2}"
BATCH_2_OUTPUT_DIR = f"{TEST_OUTPUT_DIR}/{BATCH_2}"

BATCHES = {
    BATCH_1: {"MEDHIS.PDF", "REFILL1.PDF", "ULTRA1.PDF"},
    BATCH_2: {"REFILL1.PDF", "REFILL2.PDF", "REFILL3.PDF", "ULTRA1.PDF", "ULTRA2.PDF"},
}

BATCH_NAMES = set(BATCHES)

PRESCRIPTIONS = [
    f"{BATCH_2_DIR}/REFILL1.PDF",
    f"{BATCH_2_DIR}/REFILL2.PDF",
    f"{BATCH_2_DIR}/REFILL3.PDF",
]

NON_PRESCRIPTIONS = [
    f"{BATCH_1_DIR}/MEDHIS.PDF",
    f"{BATCH_2_DIR}/ULTRA1.PDF",
    f"{BATCH_2_DIR}/ULTRA2.PDF",
]
